version: "3"

services:
  # For production
  # collectivo:
  #   container_name: collectivo
  #   build: ./collectivo_extension
  #   environment:
  #     NUXT_API_TOKEN: ${COLLECTIVO_API_TOKEN}
  #     NUXT_DIRECTUS_ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
  #     NUXT_DIRECTUS_ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
  #     NUXT_KEYCLOAK_ADMIN_CLIENT: ${KEYCLOAK_ADMIN_CLIENT}
  #     NUXT_KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_ADMIN_SECRET}
  #     NUXT_PUBLIC_COLLECTIVO_URL: ${COLLECTIVO_URL}
  #     NUXT_PUBLIC_DIRECTUS_URL: ${DIRECTUS_URL}
  #     NUXT_PUBLIC_KEYCLOAK_URL: ${KEYCLOAK_URL}
  #     NUXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     NUXT_PUBLIC_CUSTOM_VAR: ${CUSTOM_VAR}
  #   depends_on:
  #     keycloak:
  #       condition: service_healthy
  #     directus-db:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"

  directus:
    image: directus/directus:10.10.4
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/extensions:/directus/extensions
      - ./directus/uploads:/directus/uploads
    links:
      - keycloak
    depends_on:
      keycloak:
        condition: service_healthy
      directus-db:
        condition: service_healthy
    environment:
      PUBLIC_URL: ${DIRECTUS_URL}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      EXTENSIONS_AUTO_RELOAD: "true"

      DB_CLIENT: "pg"
      DB_HOST: "directus-db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: "false" # Set to true to activate caching
      CACHE_STORE: "redis"
      REDIS: "redis://directus-cache:6379"

      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_DIRECTUS_CLIENT}
      AUTH_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_DIRECTUS_SECRET}
      AUTH_KEYCLOAK_ISSUER_URL: "${KEYCLOAK_URL}/realms/collectivo/.well-known/openid-configuration"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"

      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_SAME_SITE: "lax"

      LOG_LEVEL: "debug"

      EMAIL_FROM: ${DIRECTUS_EMAIL_FROM}
      EMAIL_TRANSPORT: ${DIRECTUS_EMAIL_TRANSPORT}
      EMAIL_SMTP_HOST: ${DIRECTUS_EMAIL_SMTP_HOST}
      EMAIL_SMTP_USER: ${DIRECTUS_EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${DIRECTUS_EMAIL_SMTP_PASSWORD}

      COLLECTIVO_API_URL: ${COLLECTIVO_API_URL}
      COLLECTIVO_API_KEY: ${COLLECTIVO_API_TOKEN}
      FLOWS_ENV_ALLOW_LIST: "COLLECTIVO_API_URL, COLLECTIVO_API_TOKEN"

  directus-db:
    image: postgis/postgis:15-3.4-alpine
    volumes:
      - directus-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      POSTGRES_DB: "directus"
    ports:
      - 5432:5432

  directus-cache:
    image: redis:6

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_HOST: "keycloak-db"
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_DOMAIN}
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
      - ./keycloak/export:/tmp/export
    command: start-dev --import-realm --health-enabled true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"

  keycloak-db:
    image: postgres:15.4-alpine
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  directus-db-data:
  keycloak-db-data:
